USE SOFTBLUE;

SELECT * FROM ALUNO;
SELECT * FROM PEDIDO;

SELECT ALUNO FROM ALUNO WHERE CODIGO IN (SELECT ALUNO FROM PEDIDO);
SELECT DISTINCT(A.ALUNO) FROM ALUNO A INNER JOIN PEDIDO P ON A.CODIGO = P.ALUNO;


SELECT ALUNO FROM ALUNO WHERE CODIGO IN (SELECT ALUNO FROM PEDIDO ORDER BY DATAHORA);
SELECT DISTINCT(A.ALUNO) FROM ALUNO A INNER JOIN PEDIDO P ON A.CODIGO = P.ALUNO ORDER BY P.DATAHORA ASC LIMIT 1;
SELECT DISTINCT(A.ALUNO) FROM ALUNO A INNER JOIN PEDIDO P ON  A.CODIGO =P.ALUNO ORDER BY P.DATAHORA DESC LIMIT 1;
SELECT DISTINCT(A.ALUNO) FROM ALUNO A INNER JOIN PEDIDO P ON  A.CODIGO = P.ALUNO ORDER BY P.DATAHORA LIMIT 1 OFFSET 2;

SELECT COUNT(*) FROM PEDIDO;
SELECT SUM(VALOR) FROM PEDIDO_DETALHE;
SELECT AVG(VALOR) FROM PEDIDO_DETALHE WHERE CURSO = 2;
SELECT MAX(VALOR) FROM CURSO;
SELECT MIN(VALOR) FROM CURSO;
SELECT PEDIDO, SUM(VALOR) FROM PEDIDO_DETALHE GROUP BY PEDIDO;

SELECT I.INSTRUTOR, COUNT(*) FROM INSTRUTOR I INNER JOIN CURSO ON I.CODIGO = CURSO.INSTRUTOR GROUP BY I.INSTRUTOR;

SELECT P.CODIGO, A.ALUNO, SUM(PD.VALOR) FROM PEDIDO P 
INNER JOIN ALUNO A ON A.CODIGO = P.CODIGO 
INNER JOIN PEDIDO_DETALHE PD ON P.CODIGO = PD.PEDIDO
GROUP BY PD.PEDIDO HAVING SUM(PD.VALOR) > 500;

SELECT P.CODIGO, A.ALUNO, COUNT(PD.VALOR) FROM PEDIDO P
INNER JOIN ALUNO A ON P.ALUNO = A.CODIGO
INNER JOIN PEDIDO_DETALHE PD ON PD.PEDIDO = P.CODIGO
GROUP BY PD.PEDIDO HAVING COUNT(PD.VALOR) >= 2;

SELECT ALUNO, ENDERECO FROM ALUNO WHERE ALUNO.ENDERECO LIKE 'AV%';
SELECT CURSO FROM CURSO WHERE CURSO LIKE '%java%';

/* EXERCÍCIO 2 */

SELECT CURSO, (SELECT MIN(VALOR) FROM PEDIDO_DETALHE WHERE PEDIDO_DETALHE.CURSO = CURSO.CODIGO) AS MENOR_VALOR FROM CURSO;

SELECT CURSO FROM CURSO
WHERE TIPO IN (SELECT CODIGO FROM TIPO WHERE TIPO LIKE '%Programação%');

SELECT CURSO FROM CURSO
WHERE EXISTS (SELECT CODIGO FROM TIPO WHERE TIPO.CODIGO = CURSO.TIPO AND TIPO.TIPO= 'Programação'); 

SELECT I.INSTRUTOR, 
(SELECT SUM(PD.VALOR) FROM PEDIDO_DETALHE PD 
INNER JOIN CURSO ON CURSO.CODIGO = PD.CURSO 
WHERE CURSO.INSTRUTOR = I.CODIGO) AS SOMA_INSTR 
FROM INSTRUTOR I;


CREATE VIEW TOTAL_ALUNO AS SELECT ALUNO, (SELECT SUM(PD.VALOR) FROM PEDIDO_DETALHE PD
INNER JOIN PEDIDO ON PD.PEDIDO = PEDIDO.CODIGO
WHERE PEDIDO.ALUNO = ALUNO.CODIGO) AS TOTAL_ALUNO FROM ALUNO;

SELECT * FROM TOTAL_ALUNO;