USE SOFTBLUE;

SELECT CURSO.CURSO, TIPO.TIPO from CURSO INNER JOIN TIPO ON CURSO.TIPO = TIPO.CODIGO;
SELECT c.CURSO, TIPO.TIPO, i.INSTRUTOR, i.TELEFONE from CURSO c 
INNER JOIN TIPO ON c.TIPO = TIPO.CODIGO
INNER JOIN INSTRUTOR i ON i.codigo = c.INSTRUTOR; 


SELECT PEDIDO.CODIGO, PEDIDO.DATAHORA, PEDIDO_DETALHE.CURSO from PEDIDO INNER JOIN PEDIDO_DETALHE ON PEDIDO.CODIGO = PEDIDO_DETALHE.PEDIDO;

SELECT PEDIDO.CODIGO, PEDIDO.DATAHORA, CURSO.CURSO from PEDIDO
INNER JOIN PEDIDO_DETALHE ON PEDIDO.CODIGO = PEDIDO_DETALHE.PEDIDO
INNER JOIN CURSO ON PEDIDO_DETALHE.CURSO = CURSO.CODIGO;

SELECT PEDIDO.CODIGO, PEDIDO.DATAHORA, CURSO.CURSO, ALUNO.ALUNO from PEDIDO
INNER JOIN PEDIDO_DETALHE ON PEDIDO.CODIGO = PEDIDO_DETALHE.PEDIDO
INNER JOIN CURSO ON PEDIDO_DETALHE.CURSO = CURSO.CODIGO
INNER JOIN ALUNO ON PEDIDO.ALUNO = ALUNO.CODIGO;

CREATE VIEW preco_prog AS SELECT CURSO.CURSO, CURSO.VALOR FROM CURSO 
INNER JOIN TIPO ON CURSO.TIPO = TIPO.CODIGO
WHERE TIPO.TIPO = "Programação";

SELECT * from preco_prog;

CREATE VIEW tit_curso AS SELECT CURSO.CURSO, TIPO.TIPO, INSTRUTOR.INSTRUTOR FROM CURSO
INNER JOIN TIPO ON CURSO.TIPO = TIPO.CODIGO
INNER JOIN INSTRUTOR ON INSTRUTOR.CODIGO = CURSO.INSTRUTOR;

SELECT * FROM tit_curso;

CREATE VIEW pedidos_realizados AS SELECT PEDIDO.CODIGO, PEDIDO.DATAHORA, ALUNO.ALUNO FROM PEDIDO
INNER JOIN ALUNO ON ALUNO.CODIGO = PEDIDO.ALUNO;

SELECT * FROM pedidos_realizados;

